msco73_plate setObjectTextureGlobal [0, "scripts\plates_ukr\msco73_plate_ca.paa"];
opsn3_plate setObjectTextureGlobal [0, "scripts\plates_ukr\opsn3_plate_ca.paa"];
opsn8_plate setObjectTextureGlobal [0, "scripts\plates_ukr\opsn8_plate_ca.paa"];
odsbr82_plate setObjectTextureGlobal [0, "scripts\plates_ukr\odsbr82_plate_ca.paa"];
obrmp36_plate setObjectTextureGlobal [0, "scripts\plates_ukr\obrmp36_plate_ca.paa"];
ogshbr128_plate setObjectTextureGlobal [0, "scripts\plates_ukr\ogshbr128_plate_ca.paa"];
oshb425_plate setObjectTextureGlobal [0, "scripts\plates_ukr\oshb425_plate_ca.paa"];
ombr47_plate setObjectTextureGlobal [0, "scripts\plates_ukr\ombr47_plate_ca.paa"];
psu_plate setObjectTextureGlobal [0, "scripts\plates_ukr\psu_plate_ca.paa"];